"""The WKB/EWKB <-> GeoJSON <-> EWKT codec in `fastfort/admin/geo.py`.

Fixtures below are hex generated by PostGIS itself (`ST_AsBinary`/`ST_AsEWKB`,
both byte orders, `ST_SetSRID(..., 4326)` for the EWKB ones) rather than
hand-written, so a bug in this module's own encoder could not also be baked
into the fixture that is supposed to catch it. `POINT_WKB_LE`/`POINT_EWKB_LE`
below are the same two hex strings the geometry tests used before this module
existed (`TASHKENT_WKB`/`TASHKENT_EWKB`), confirming nothing moved.
"""

from __future__ import annotations

import pytest

from fastfort.spec import FieldSpec, FieldType, GeometrySpec, geo

# ---------------------------------------------------------------------------
# Fixtures: a point in Tashkent (69.2401 E, 41.2995 N), and a handful of
# larger shapes built around the same coordinates, in both byte orders and
# with/without the EWKB SRID prefix.
# ---------------------------------------------------------------------------

POINT_WKB_LE = "010100000041F163CC5D4F51407593180456A64440"
POINT_WKB_BE = "000000000140514F5DCC63F1414044A65604189375"
POINT_EWKB_LE = "0101000020E610000041F163CC5D4F51407593180456A64440"
POINT_EWKB_BE = "0020000001000010E640514F5DCC63F1414044A65604189375"

LINESTRING_WKB_LE = (
    "01020000000300000041F163CC5D4F51407593180456A6444033333333335351406666"
    "666666A644406666666666565140295C8FC2F5A84440"
)
LINESTRING_WKB_BE = (
    "00000000020000000340514F5DCC63F1414044A6560418937540515333333333334044"
    "A6666666666640515666666666664044A8F5C28F5C29"
)

POLYGON_WKB_LE = (
    "01030000000100000005000000CDCCCCCCCC4C51409A999999999944403333333333535140"
    "9A9999999999444033333333335351406666666666A64440CDCCCCCCCC4C51406666666666"
    "A64440CDCCCCCCCC4C51409A99999999994440"
)
POLYGON_WKB_BE = (
    "0000000003000000010000000540514CCCCCCCCCCD404499999999999A4051533333333333"
    "404499999999999A40515333333333334044A6666666666640514CCCCCCCCCCD4044A66666"
    "66666640514CCCCCCCCCCD404499999999999A"
)

MULTIPOINT_WKB_LE = (
    "010400000002000000010100000041F163CC5D4F51407593180456A64440010100000033"
    "333333335351406666666666A64440"
)

MULTILINESTRING_WKB_LE = (
    "010500000002000000010200000002000000CDCCCCCCCC4C51409A99999999994440333333"
    "33335351409A999999999944400102000000030000009A999999995951403333333333B344"
    "4000000000006051400000000000C044406666666666665140CDCCCCCCCCCC4440"
)

MULTIPOLYGON_WKB_LE = (
    "01060000000200000001030000000100000004000000CDCCCCCCCC4C51409A999999999944"
    "4033333333335351409A9999999999444033333333335351406666666666A64440CDCCCCCC"
    "CC4C51409A9999999999444001030000000100000004000000CDCCCCCCCC8C51409A999999"
    "9919454033333333339351409A9999999919454033333333339351406666666666264540CD"
    "CCCCCCCC8C51409A99999999194540"
)

GEOMETRYCOLLECTION_WKB_LE = (
    "010700000002000000010100000041F163CC5D4F51407593180456A64440010200000002"
    "000000CDCCCCCCCC4C51409A9999999999444033333333335351406666666666A64440"
)


def field(kind: str = "GEOMETRY", srid: int = 4326) -> FieldSpec:
    return FieldSpec(
        name="loc",
        label="Loc",
        type=FieldType.GEOMETRY,
        geometry=GeometrySpec(kind=kind, srid=srid),
    )


# ---------------------------------------------------------------------------
# decode(): WKB and EWKB, both byte orders, every geometry kind
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("raw", [POINT_WKB_LE, POINT_WKB_BE, POINT_EWKB_LE, POINT_EWKB_BE])
def test_decode_point_both_byte_orders_with_and_without_srid(raw: str) -> None:
    assert geo.decode(raw) == {"type": "Point", "coordinates": [69.2401, 41.2995]}


@pytest.mark.parametrize("raw", [LINESTRING_WKB_LE, LINESTRING_WKB_BE])
def test_decode_linestring(raw: str) -> None:
    assert geo.decode(raw) == {
        "type": "LineString",
        "coordinates": [[69.2401, 41.2995], [69.3, 41.3], [69.35, 41.32]],
    }


@pytest.mark.parametrize("raw", [POLYGON_WKB_LE, POLYGON_WKB_BE])
def test_decode_polygon(raw: str) -> None:
    result = geo.decode(raw)
    assert result is not None
    assert result["type"] == "Polygon"
    assert len(result["coordinates"][0]) == 5  # a closed ring: 4 corners + repeat


def test_decode_multipoint() -> None:
    assert geo.decode(MULTIPOINT_WKB_LE) == {
        "type": "MultiPoint",
        "coordinates": [[69.2401, 41.2995], [69.3, 41.3]],
    }


def test_decode_multilinestring() -> None:
    result = geo.decode(MULTILINESTRING_WKB_LE)
    assert result is not None
    assert result["type"] == "MultiLineString"
    assert len(result["coordinates"]) == 2


def test_decode_multipolygon() -> None:
    result = geo.decode(MULTIPOLYGON_WKB_LE)
    assert result is not None
    assert result["type"] == "MultiPolygon"
    assert len(result["coordinates"]) == 2


def test_decode_geometrycollection() -> None:
    result = geo.decode(GEOMETRYCOLLECTION_WKB_LE)
    assert result is not None
    assert result["type"] == "GeometryCollection"
    assert [g["type"] for g in result["geometries"]] == ["Point", "LineString"]


def test_decode_reads_a_wkbelement_style_object_off_desc() -> None:
    """A GeoAlchemy2 `WKBElement`'s `str()` is its hex -- `.desc` is read
    directly instead, so this module never needs to import GeoAlchemy2 to
    check."""

    class FakeWKBElement:
        desc = POINT_EWKB_LE

    assert geo.decode(FakeWKBElement()) == {"type": "Point", "coordinates": [69.2401, 41.2995]}


def test_an_undecodable_geometry_returns_none_rather_than_raising() -> None:
    """A polygon is not editable as two numbers, but a shape this module
    cannot make sense of must not take the page down either."""
    assert geo.decode("not hex at all") is None
    assert geo.decode("") is None
    assert geo.decode("ff") is None  # valid hex, far too short to be a geometry


# ---------------------------------------------------------------------------
# to_ewkt() / round trip through decode()
# ---------------------------------------------------------------------------


def test_to_ewkt_a_point() -> None:
    geojson = {"type": "Point", "coordinates": [69.2401, 41.2995]}
    assert geo.to_ewkt(geojson, 4326) == "SRID=4326;POINT(69.2401 41.2995)"


def test_geometries_round_trip_through_ewkt_and_back() -> None:
    for raw in (
        POINT_EWKB_LE,
        LINESTRING_WKB_LE,
        POLYGON_WKB_LE,
        MULTIPOINT_WKB_LE,
        MULTILINESTRING_WKB_LE,
        MULTIPOLYGON_WKB_LE,
        GEOMETRYCOLLECTION_WKB_LE,
    ):
        original = geo.decode(raw)
        assert original is not None
        ewkt = geo.to_ewkt(original, 4326)
        srid, body = ewkt.split(";", 1)
        assert srid == "SRID=4326"
        # `_try_wkt` is private, but round-tripping through it is the only way
        # to confirm the WKT this module writes is also WKT this module reads.
        reparsed = geo._try_wkt(body)
        assert reparsed == original


# ---------------------------------------------------------------------------
# parse(): lat/lng, WKT, EWKT, GeoJSON -- in that order
# ---------------------------------------------------------------------------


def test_parse_lat_lng_is_written_latitude_first() -> None:
    """Every map, phone and street sign puts latitude first. WKT does not,
    which is exactly the trap this converts away from."""
    assert geo.parse("41.2995, 69.2401", field()) == "SRID=4326;POINT(69.2401 41.2995)"


@pytest.mark.parametrize(
    ("text", "message"),
    [
        ("nowhere", "latitude and a longitude"),
        ("41.2995", "latitude and a longitude"),
        ("91, 0", "-90 to 90"),
        ("0, 200", "-180 to 180"),
    ],
)
def test_parse_lat_lng_that_is_not_one_says_why(text: str, message: str) -> None:
    with pytest.raises(ValueError, match=message):
        geo.parse(text, field())


def test_parse_lat_lng_range_check_only_applies_at_srid_4326() -> None:
    """Meaningless outside EPSG:4326 -- in a projected system like 3857 the
    numbers are metres, and 500 is an ordinary coordinate, not a latitude."""
    assert geo.parse("500, 12000", field(srid=3857)) == "SRID=3857;POINT(12000 500)"


def test_parse_accepts_plain_wkt_using_the_columns_srid() -> None:
    assert geo.parse("POINT(69.2401 41.2995)", field()) == "SRID=4326;POINT(69.2401 41.2995)"


def test_parse_accepts_ewkt_and_keeps_its_own_srid() -> None:
    assert geo.parse("SRID=3857;POINT(100 200)", field(srid=4326)) == "SRID=3857;POINT(100 200)"


def test_parse_accepts_geojson_longitude_first() -> None:
    """GeoJSON is `[longitude, latitude]` per RFC 7946 -- the one shape in this
    module where the order is not "latitude first"."""
    text = '{"type": "Point", "coordinates": [69.2401, 41.2995]}'
    assert geo.parse(text, field()) == "SRID=4326;POINT(69.2401 41.2995)"


def test_parse_a_multi_point_shape_via_wkt() -> None:
    text = "POLYGON((69.2 41.2, 69.3 41.2, 69.3 41.3, 69.2 41.3, 69.2 41.2))"
    assert geo.parse(text, field(kind="POLYGON")) == f"SRID=4326;{text}"


def test_parse_rejects_a_shape_the_column_does_not_want() -> None:
    """Writing a POLYGON into a POINT column is a database error this catches
    first, naming what the column actually wants."""
    text = "POLYGON((0 0, 1 0, 1 1, 0 0))"
    with pytest.raises(ValueError, match="takes a Point"):
        geo.parse(text, field(kind="POINT"))


def test_parse_that_is_nothing_recognisable_says_so() -> None:
    with pytest.raises(ValueError, match="latitude and a longitude"):
        geo.parse("this is not a shape", field())


# ---------------------------------------------------------------------------
# render(): the form control's text -- a point renders lat/lng, everything
# else renders EWKT so a value nobody touched still saves cleanly.
# ---------------------------------------------------------------------------


def test_render_a_point() -> None:
    assert geo.render(POINT_EWKB_LE, field()) == "41.2995, 69.2401"


def test_render_round_trips_through_parse() -> None:
    for raw, kind in (
        (POINT_EWKB_LE, "POINT"),
        (POLYGON_WKB_LE, "POLYGON"),
        (MULTIPOLYGON_WKB_LE, "MULTIPOLYGON"),
        (GEOMETRYCOLLECTION_WKB_LE, "GEOMETRYCOLLECTION"),
    ):
        spec = field(kind=kind)
        rendered = geo.render(raw, spec)
        # A value nobody touched has to save cleanly when the form posts back
        # exactly what it was shown.
        assert geo.parse(rendered, spec) == geo.to_ewkt(geo.decode(raw), 4326)  # type: ignore[arg-type]


def test_render_an_undecodable_geometry_falls_back_rather_than_raising() -> None:
    assert geo.render("not hex at all", field()) == "not hex at all"


# ---------------------------------------------------------------------------
# summarise(): the list-cell text -- a human summary, not required to
# round-trip.
# ---------------------------------------------------------------------------


def test_summarise_a_point() -> None:
    assert geo.summarise(POINT_EWKB_LE) == "41.2995, 69.2401"


def test_summarise_a_linestring_as_a_route_length() -> None:
    result = geo.summarise(LINESTRING_WKB_LE)
    assert result.startswith("Route · ")
    assert result.endswith(" km")


def test_summarise_a_polygon_as_a_point_count() -> None:
    assert geo.summarise(POLYGON_WKB_LE) == "Polygon · 5 points"


def test_summarise_a_multipolygon_as_a_part_count() -> None:
    assert geo.summarise(MULTIPOLYGON_WKB_LE) == "Multipolygon · 2 parts"


def test_summarise_a_geometrycollection_as_a_shape_count() -> None:
    assert geo.summarise(GEOMETRYCOLLECTION_WKB_LE) == "Collection · 2 shapes"


def test_summarise_an_undecodable_geometry_falls_back_rather_than_raising() -> None:
    """A polygon is not editable as two numbers, but it must not take the page
    down either."""
    assert geo.summarise("not hex at all") == "not hex at all"
